### ISSUE TITLE
Epic: Moving to microservice architecture

### ISSUE THREAD

**Issue by ovr** [cube-js/cube.js#1167]
Hello!

#### Motivation

When we looked at embedding Cube.js in Express, we learned that Cube.js should be scaled very differently vs. other parts of Express, and embedding Cube.js is not the right approach in the long term, especially for larger deployments. 

As a result, we will make several updates to change the Cube.js-Express relationship, and embedding will no longer be a recommended way to deploy Cube.js. 

The goal is to: 

- Make Cube.js a standalone service so it doesn't share process resource with other apps (e.g. Express). 
- Introduce the Official Docker image
- Provide a new DX by easy configuration on top of JavaScript(JS)/TypeScript(TS) inside `cube.js`/`cube.ts` file.

Related blog post: https://cube.dev/blog/cubejs-loves-docker/

#### Plan

- [x] Introduce Docker images
- [x] Research ability to use `ts` files as configuration (for compile on-the-fly)
- [x] Add the new template (`docker`) to cubejs-cli and use it by default
- [x] Add diagnostics inside CLI for dev-server/server commands to detect problems with project configuration
- [x] Add health checks (+ add it inside `Dockerfile`)

#### Documentation

- Update documentation
- Update examples

#### Related Issues/PRs

- [Introduce official docker image](https://github.com/cube-js/cube.js/pull/1201)
- [Add external command support](https://github.com/cube-js/cube.js/pull/1221)
- [Introduce Docker template](https://github.com/cube-js/cube.js/pull/1243) 
- [Implement dev server & server command](https://github.com/cube-js/cube.js/pull/1227)

Thanks!
