### ISSUE TITLE
Epic: Angular integration for Cube.js

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube.js#1289]
This is an Epic issue for Angular Query Builder in Cube.js. 

#### Motivation 
We want to better support Angular framework users so that there is an easy integration of Cube.js into Angular apps (similar to the way it is with other frameworks such as React). 

The goal is to: 

- [x] Add Angular Query Builder (similar to`@cubejs-client/react` & `@cubejs-client/vue`).  
- [x] Add Angular code generation to the Playground
- [ ] Include updates to relevant templates and guides. 

#### Related issues/PRs: 
- [Query Builder and Query Renderer for Angular](https://github.com/cube-js/cube.js/issues/832) 
- [Angular Query Builder PR](https://github.com/cube-js/cube.js/pull/1073)
- Angular material guide
  - https://github.com/cube-js/cube.js/pull/1223
  - https://github.com/cube-js/cube.js/pull/1258  
- [Dynamic Angular template](https://github.com/cube-js/cube.js/pull/1257)
