### ISSUE TITLE
Epic: Vue integration for Cube.js

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube.js#1322]
This is an Epic issue for Vue integration for Cube.js. 

#### Motivation 
We want to better support Vue.js framework users so that there is an easy integration of Cube.js into Vue apps (similar to the way it is with other frameworks such as React). For the Query Builder, we want to wrap-up our work so that it has all the features that the React's Query Builder has. 

The goal/plan is to: 

- [x] Finish the Query Builder work.  
- [x] Build the Dynamic Vue Dashboard.
- [x] Add the Vue Dashboard to the Playground.
- [ ] Vue code generation.

#### Related issues/PRs:

**Comment by rpaik** [comment]
Moving this to Q1'2021 as we're not able to complete this in Q4.
