### ISSUE TITLE
Epic: Streamline authentication & authorization

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube.js#1738]
This is an Epic issue to streamline authentication & authorization.

**Motivation** 

- There are some discrepancies in auth-related APIs. 
- Implementing support for common auth providers requires boilerplate code. 
- It is hard to develop and debug authorization and security context. 
- Currently, there are multiple ways to implement custom auth with Cube.js which creates uncertainty on what the best practices are and creates opportunities for bad design decisions.

**Goals/plans**

- [x] Unify and streamline auth-related APIs.
- [x] Common authentication methods work out-of-the-box on Cube.js. For example explore the idea of creating plug-n-play packages for setting up authentication for different services (e.g. `@cubejs-auth/jwt`, `@cubejs-auth/auth0`, `@cubejs-auth/aws-cognito` etc.). 
- [x] JWT and security context management in Playground. 
- [x] Improve APIs for custom auth logic and provide corresponding documentation and examples.
- [x] Improve overall auth-related documentation and provide examples for common auth patterns.
