### ISSUE TITLE
Epic: New rollup pre-aggregations

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube.js#3106]
Facilitate defining new rollup pre-aggregations by working on: 

- [ ] Iterate on the rollup designer. 
- [ ] Improve error messages.  
- [ ] Contribute to increased adoption of pre-aggregations by Cube.js users.
